# docker-compose.test.yml
version: "3.9"
services:
  postgres:
    image: postgres:18beta3-alpine3.22
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: atlas_test
    ports:
      - "5433:5432"
